### ISSUE TITLE
Problems in click training.

### ISSUE THREAD

**Issue by byhwhite** [MedicineToken/Medical-SAM2#1]
Dear Authors,

Thank you for your prompt work on fine-tuning SAM2 for medical imaging. I am attempting to run your framework, but some bugs have occurred, taking a long time to debug😢
Hope you can complete your code as soon as possible, so that other works can have a fair comparison.

Thank you!

**Comment by WuJunde** [comment]
no problem on our side, you mean 2d or 3d?

**Comment by byhwhite** [comment]
> no problem on our side, you mean 2d or 3d?

I'm tring 3d click training. After reading your dataset function for 3d, I'v processed BTCV by myself. Perhaps the code version uploaded is not the newest？

**Comment by jiayuanz3** [comment]
Sorry for any inconvenience! I've just updated 2D example case and the 3D example will be updated soon!
