### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### ISSUE THREAD

**Issue by 1161213455** [MedicineToken/Medical-SAM2#10]
I encountered an error while installing the environment with the command conda env create -f environment.yml and running the 3D case。

Error：
Traceback (most recent call last):
  File "/disk/projects/Medical-SAM2/train_3d.py", line 115, in <module>
    main()
  File "/disk/projects/Medical-SAM2/train_3d.py", line 98, in main
    loss, prompt_loss, non_prompt_loss = function.train_sam(args, net, optimizer1, optimizer2, nice_train_loader, epoch)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/disk/projects/Medical-SAM2/func_3d/function.py", line 114, in train_sam
    _, _, _ = net.train_add_new_bbox(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/disk/projects/Medical-SAM2/sam2_train/sam2_video_predictor.py", line 439, in train_add_new_bbox
    out_frame_idx, out_obj_ids, out_mask_logits = self.train_add_new_points(
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/disk/projects/Medical-SAM2/sam2_train/sam2_video_predictor.py", line 523, in train_add_new_points
    current_out, _ = self._run_single_frame_inference(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/disk/projects/Medical-SAM2/sam2_train/sam2_video_predictor.py", line 1351, in _run_single_frame_inference
    pred_masks_gpu = fill_holes_in_mask_scores(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/disk/projects/Medical-SAM2/sam2_train/utils/misc.py", line 255, in fill_holes_in_mask_scores
    is_hole = (labels > 0) & (areas <= max_area)
               ^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

System environment
**lsb_release -a**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
**nvcc -V**
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:19:38_PST_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0
 **conda -V**
conda 23.5.0
**nvidia-smi**
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.107.02             Driver Version: 550.107.02     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090        Off |   00000000:01:00.0 Off |                  N/A |
| 35%   55C    P0             N/A /  350W |       1MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

**Comment by jiayuanz3** [comment]
I'm not sure whether it's related to the [Issue11](https://github.com/MedicineToken/Medical-SAM2/issues/11) mentioned here.  TORCH_USE_CUDA_DSA occurs when the code is attempting to run on a GPU, but the installed PyTorch version, CUDA toolkit, or GPU driver is incompatible with the device's architecture. Here's the environments we've tested on:
`Operating System: Ubuntu 22.04
Conda Version: 23.7.4
Python Version: 3.12.4`
