### ISSUE TITLE
Remove personal path

### ISSUE THREAD

**Issue by benedictgroves** [MedicineToken/Medical-SAM2#11]
Line 215 of environment.yml contains authors local filepath to conda env 'prefix: /home/leo/anaconda3/envs/medsam2'. This could cause an issue on user machines with connection to conda envs. Would recommend deleting.

https://github.com/MedicineToken/Medical-SAM2/blob/b63734bb448458d528c7bb495852289002f284f0/environment.yml#L215 

Ben

**Comment by jiayuanz3** [comment]
Thanks for your advice! It's updated now.
