### ISSUE TITLE
Checkpoints issue

### ISSUE THREAD

**Issue by bspass0** [MedicineToken/Medical-SAM2#13]
Thank you for your work on the model!

When trying to run the checkpoint file with bash I have the following error: 

$ cd checkpoints
bash download_ckpts.sh
Downloading sam2_hiera_tiny.pt checkpoint...
download_ckpts.sh: line 20: wget: command not found
Failed to download checkpoint from https://dl.fbaipublicfiles.com/segment_anything_2/072824/sam2_hiera_tiny.pt

And this is the message when accessing the URL directly:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>CHG0JWSD8DDSWEEN</RequestId>
<HostId>+Zia+nffTq4xbvpcCiWxhQc/R62zgPYXDa2qJcigatCMbCi3h/Wxo+6y0h89/T/OlEqQ/Fz33v7yR9ILjkhGxg==</HostId>
</Error>

Are the checkpoints required to run the train_3d.py with a decent DICE score?

**Comment by jiayuanz3** [comment]
Could you try without bash file to see whether it works or not? This instruction follows **SAM2 Getting Started** workflow (https://github.com/facebookresearch/segment-anything-2). Or you can download the weight individually, as shown in SAM2 **Getting Started**  session.

**Comment by bspass0** [comment]
Thank you. It worked after I installed WSL 2 Ubuntu 22.04 and ran from VS code WSL Ubuntu distro.
