### ISSUE TITLE
Dataset Format for the Training Task

### ISSUE THREAD

**Issue by AlicanAKCA** [MedicineToken/Medical-SAM2#20]
Hi, congrats for the great work.
Is there any information about the exact dataset format for Medical-SAM2?
Thanks in advance.

**Comment by jiayuanz3** [comment]
Here are the dataloader for 2d and 3d case: https://github.com/MedicineToken/Medical-SAM2/blob/main/func_2d/dataset.py ; https://github.com/MedicineToken/Medical-SAM2/blob/main/func_3d/dataset/btcv.py. so make sure your own dataloader provide similar information, e.g. 'image', 'mask' etc. for the dataset itself, you can download the dataset we mentioned in readme to get a view.
