### ISSUE TITLE
请问如何在python3.10下编译运行train_3d.py

### ISSUE THREAD

**Issue by yuren1024** [MedicineToken/Medical-SAM2#22]
我在python3.10下运行train_3d.py得到了一个报错，
ImportError: Python version mismatch: module was compiled for Python 3.12, but the interpreter version is incompatible: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0].

修改环境是一件麻烦的事情，我想询问是否有快捷的方法，如果没有的话我会在python3.12上重新搭建环境。

**Comment by yuren1024** [comment]
我解决了

**Comment by 1iushuran** [comment]
> 我解决了
 您好，请问您怎么解决的，是重新搭建了环境嘛，我们想要在google colab里运行，也是遇到了这个incompatible python 3.12的问题。请问您这边是用了什么方法解决的，感谢打扰了🙏
