### ISSUE TITLE
Unable to build environment using environment.yml file

### ISSUE THREAD

**Issue by JamesBurgess98** [MedicineToken/Medical-SAM2#3]
I am unable to build the environment using the provided environment.yml file. 
Operating System: Windows 11
Conda Version: 24.5.0
Python Version: 3.12.4

The process fails with the following error message after env creation command (conda env create -f environment.yml) in the Medical-SAM2 directory: 
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides requested zlib ==1.2.13 h5eee18b_1
  - nothing provides requested zeromq ==4.3.5 h6a678d5_0
  - nothing provides requested xz ==5.4.6 h5eee18b_1
  - nothing provides requested wheel ==0.43.0 py312h06a4308_0
  - nothing provides requested tornado ==6.4.1 py312h5eee18b_0
  - nothing provides requested tk ==8.6.14 h39e8969_0
  - nothing provides requested sqlite ==3.45.3 h5eee18b_0
  - nothing provides requested setuptools ==69.5.1 py312h06a4308_0
  - nothing provides requested readline ==8.2 h5eee18b_0
  - nothing provides requested pyzmq ==25.1.2 py312h6a678d5_0
  - nothing provides requested python ==3.12.4 h5148396_1
  - nothing provides requested pip ==24.0 py312h06a4308_0
  - nothing provides requested openssl ==3.0.14 h5eee18b_0
  - nothing provides requested ncurses ==6.4 h6a678d5_0
  - nothing provides requested libuuid ==1.41.5 h5eee18b_0
  - nothing provides requested libstdcxx-ng ==11.2.0 h1234567_1
  - nothing provides requested libsodium ==1.0.18 h36c2ea0_1
  - nothing provides requested libgomp ==11.2.0 h1234567_1
  - nothing provides requested libgcc-ng ==11.2.0 h1234567_1
  - nothing provides requested libffi ==3.4.4 h6a678d5_1
  - nothing provides requested ld_impl_linux-64 ==2.38 h1181459_1
  - nothing provides requested jupyter_core ==5.7.2 py312h06a4308_0
  - nothing provides __unix needed by ipython-8.26.0-pyh707e725_0
  - nothing provides __linux needed by ipykernel-6.29.5-pyh3099207_0
  - nothing provides requested expat ==2.6.2 h6a678d5_0
  - nothing provides requested debugpy ==1.6.7 py312h6a678d5_0
  - nothing provides requested ca-certificates ==2024.7.4 hbcca054_0
  - nothing provides requested bzip2 ==1.0.8 h5eee18b_6
  - nothing provides requested _openmp_mutex ==5.1 1_gnu

Could not solve for environment specs
The following packages are incompatible
├─ _openmp_mutex ==5.1 1_gnu does not exist (perhaps a typo or a missing channel);
├─ bzip2 ==1.0.8 h5eee18b_6 does not exist (perhaps a typo or a missing channel);
├─ ca-certificates ==2024.7.4 hbcca054_0 does not exist (perhaps a typo or a missing channel);
├─ debugpy ==1.6.7 py312h6a678d5_0 does not exist (perhaps a typo or a missing channel);
├─ expat ==2.6.2 h6a678d5_0 does not exist (perhaps a typo or a missing channel);
├─ ipykernel ==6.29.5 pyh3099207_0 is not installable because it requires
│  └─ __linux, which is missing on the system;
├─ ipython ==8.26.0 pyh707e725_0 is not installable because it requires
│  └─ __unix, which is missing on the system;
├─ jupyter_core ==5.7.2 py312h06a4308_0 does not exist (perhaps a typo or a missing channel);
├─ ld_impl_linux-64 ==2.38 h1181459_1 does not exist (perhaps a typo or a missing channel);
├─ libffi ==3.4.4 h6a678d5_1 does not exist (perhaps a typo or a missing channel);
├─ libgcc-ng ==11.2.0 h1234567_1 does not exist (perhaps a typo or a missing channel);
├─ libgomp ==11.2.0 h1234567_1 does not exist (perhaps a typo or a missing channel);
├─ libsodium ==1.0.18 h36c2ea0_1 does not exist (perhaps a typo or a missing channel);
├─ libstdcxx-ng ==11.2.0 h1234567_1 does not exist (perhaps a typo or a missing channel);
├─ libuuid ==1.41.5 h5eee18b_0 does not exist (perhaps a typo or a missing channel);
├─ ncurses ==6.4 h6a678d5_0 does not exist (perhaps a typo or a missing channel);
├─ openssl ==3.0.14 h5eee18b_0 does not exist (perhaps a typo or a missing channel);
├─ readline ==8.2 h5eee18b_0 does not exist (perhaps a typo or a missing channel);
├─ setuptools ==69.5.1 py312h06a4308_0 does not exist (perhaps a typo or a missing channel);
├─ sqlite ==3.45.3 h5eee18b_0 does not exist (perhaps a typo or a missing channel);
├─ tk ==8.6.14 h39e8969_0 does not exist (perhaps a typo or a missing channel);
├─ tornado ==6.4.1 py312h5eee18b_0 does not exist (perhaps a typo or a missing channel);
├─ wheel ==0.43.0 py312h06a4308_0 does not exist (perhaps a typo or a missing channel);
├─ xz ==5.4.6 h5eee18b_1 does not exist (perhaps a typo or a missing channel);
├─ zeromq ==4.3.5 h6a678d5_0 does not exist (perhaps a typo or a missing channel);
└─ zlib ==1.2.13 h5eee18b_1 does not exist (perhaps a typo or a missing channel).

**Comment by jiayuanz3** [comment]
Thanks for pointing out! We've updated the environment.yml file and double checked the installation process. Could you retry to see if it works now?

**Comment by JamesBurgess98** [comment]
Unfortunately still getting the same error message

**Comment by li-pengcheng** [comment]
No matching distribution found for sam-2

**Comment by shujuecn** [comment]
When I tried to set up this environment on `Mac OS 14.5`, I encountered the same error. However, it worked successfully on `Ubuntu 22.04` under `WSL2`. 
I suggest that the author @jiayuanz3  provide more detailed information about the system environment in the `Install the environment` section to help reduce such issues.

**Comment by li-pengcheng** [comment]
> No matching distribution found for sam-2

这个要预先编译meta的官方库https://github.com/facebookresearch/segment-anything-2，然后可以自己pip装其他的库。

**Comment by jiayuanz3** [comment]
Sorry for the late reply. We tested on the following system environment:
```
Operating System: ubuntu 22.04
Conda Version: 23.7.4
Python Version: 3.12.4
```
some issues may occur due to different system environment 😢
