### ISSUE TITLE
是否支持无标签预测？

### ISSUE THREAD

**Issue by cxmDREAM** [MedicineToken/Medical-SAM2#31]
在train.py文件中，训练模型时需要依赖于通过click或bbox生成的label，进而生成mask用于模型的训练。
我的工作需求是将脑的MRI影像中所有的部位全部分割出来，例如脑室区域、脑干区域、脑脊液。
在medical-sam2中，我使用任意患者数据进行预测的时候也必须通过click或bbox才能预测到结果吗？
是否可以全自动无标签的进行分割？如果不可以，我能否通过某个患者的一次bbox的结果mask，复制到其他患者的mask文件中对其他患者进行预测。
                                                                                                                                             希望可以得到作者的回复，提前感谢！

**Comment by jiayuanz3** [comment]
it can support no prompt inference, but the performance will be worse than provided. as there are large variability in different individuals (most cases), I'm not sure to what extent the provided mask from one individual will improve the performance

**Comment by JaxnBai** [comment]
你好，请问这个问题是怎么解决的。
我现在训练完之后，想要参考验证函数写一个推理生成函数，但是没有bbox，想参考一下你是怎么做的
