### ISSUE TITLE
Is there code for segmentation visualization?

### ISSUE THREAD

**Issue by Moliang-Wange** [MedicineToken/Medical-SAM2#32]
Hi,

I was looking through the README and noticed the impressive video segmentation visualization result in 3D Abdomen Segmentation Visualisation. Now I can use your code for inference, but I would like to visualize the segmentation result like the one shown in README.

I was wondering if there is any existing code in this project for visualizing segmentation results like this? If so, could you please point me to the relevant files or functions? 

If not, could you provide some details on how this visualization was generated (e.g., tools or libraries used, how to overlay different segmentation regions on the original image, etc.)?

Thank you for your help!

**Comment by jiayuanz3** [comment]
you can turn on the visualisation by add **-vis 1** in the command line for 3d case. the visualisation prediction results are saved in a folder named temp (you can change the path in the function.py). the subfolder is named by image names, the subsubfolder is named by frame index, subsubfolder by object index as provided during training. given this predictions, you can easily mapping them with python code as the one shown in demo.
