### ISSUE TITLE
Implementation of weighted pick up strategy and 'confidence-first'

### ISSUE THREAD

**Issue by jacoblam3112** [MedicineToken/Medical-SAM2#33]
While going through the code, I have two questions that I would really appreciate if you could help explain:

1) In validation_sam() method inside the function.py file, I could not find the code that explicitly implements the weighted pickup strategy. Could you point out which part of the code takes care of that ?

2) Also I do not see how the 'confidence-first' memory is implemented in the code ? Although I do see the memory bank being filled with diverse input features through similarity calculation.
Thank you for your help in advance.

**Comment by jiayuanz3** [comment]
thanks for reaching out. 
1. we've now pushed the version with weighted pickup and related code is around here https://github.com/MedicineToken/Medical-SAM2/blob/ccc234ed578a41e80ab1cdb11632b544a2544a48/func_2d/function.py#L343
2. 'confidence-first' memory is a standard we defined by both similarity (as you mention) and the prediction quality around here https://github.com/MedicineToken/Medical-SAM2/blob/ccc234ed578a41e80ab1cdb11632b544a2544a48/func_2d/function.py#L439. it ensures that the memory bank stores high quality and diverse templates.
