### ISSUE TITLE
Support for One-Prompt segmentation

### ISSUE THREAD

**Issue by rahidfayad** [MedicineToken/Medical-SAM2#35]
In `function.py`, I noticed that the `validation_sam` function is used for performing inference. However, I was wondering if there is a way to segment a new image without prompting and using instead a one-shot example.

Specifically, I am looking a One-prompt approach as described in the paper, where a query image is segmented based on a template image and its corresponding prompt. Could you provide guidance on how to implement this, or is there a built-in function that supports this use case?

**Comment by jiayuanz3** [comment]
Yes, you can achieve one-prompt by modifying after this line:
https://github.com/MedicineToken/Medical-SAM2/blob/ccc234ed578a41e80ab1cdb11632b544a2544a48/func_2d/function.py#L367.

In the current code, the prompt is given every 5 images. for an entire one-prompt behaviour  (i.e. prompt only given to the first image), change 5 to a larger number to ensure only the first image is given the prompt.
