### ISSUE TITLE
The results that I produced using REFUGE_disc is worse than REFUGE_cup

### ISSUE THREAD

**Issue by tldiscexpt** [MedicineToken/Medical-SAM2#39]
To use the disc images in the REFUGE dataset, I modified these codes from:
```
img_path = os.path.join(subfolder, name + '_cropped.jpg')
multi_rater_cup_path = [os.path.join(subfolder, name + '_seg_cup_' + str(i) + '_cropped.jpg') for i in range(1, 8)]
```
to:
```
img_path = os.path.join(subfolder, name + '.jpg')
multi_rater_cup_path = [os.path.join(subfolder, name + '_seg_disc_' + str(i) + '.png') for i in range(1, 8)]
```
All other codes remained the same. I trained for 100 epochs. For cup in cropped image, I achieved DICE 0.866 and IoU 0.776, score of 0.125. While for disc images, I achieved DICE 0.825 and IoU 0.725, score of 0.028. I tried sam2_hiera_small and sam2_hiera_large, the results were similar.

There must be something wrong with my code modifications, or there may be fine-tuning steps that I missed. Could you provide some help on this?

**Comment by saugatkandel** [comment]
@tldiscexpt  I am also seeing the same results. Did you see any improvement?
