### ISSUE TITLE
May I ask how to conduct a separate test (testing a sample)？

### ISSUE THREAD

**Issue by LvNianZu** [MedicineToken/Medical-SAM2#44]
May I ask how to conduct a separate test (testing a sample)？

**Comment by jiayuanz3** [comment]
thanks for reaching out. you can directly run 2d validation/testing from this line here https://github.com/MedicineToken/Medical-SAM2/blob/48975419fb65820fbd02dd86f46ce3a561a5a785/train_2d.py#L108. apologise we didn't write a separate file, but everything is the same except hiding the train_sam in L103 above. If testing from a pretrained weight, replace -sam_ckpt in the args with your saved weight path.
