### ISSUE TITLE
use SAM-L or SAM-B

### ISSUE THREAD

**Issue by Asagami-Fujino** [MedicineToken/Medical-SAM2#45]
Thanks for your work! In your project I can find that you've used SAM-T and SAM-S, I'm wondering if using SAM-L or SAM-B can improve the performance. How to generate sam2_hiera_b/l.yaml that can work in your project?

**Comment by jiayuanz3** [comment]
the configuration file should be same from SAM2 https://github.com/facebookresearch/segment-anything-2/tree/main/sam2_configs. the checkpoints should be downloaded with T and S, stored in the checkpoints folder.
