### ISSUE TITLE
3D medical image processing

### ISSUE THREAD

**Issue by Vanityplunde** [MedicineToken/Medical-SAM2#57]
hello！
Is the model only able to process ".jpg", ".jpeg", ".JPG", and ".JPEG" formats? Can segmentation be performed directly on .nii files? Does 3D segmentation refer to a time series of 2D slices?

**Comment by jiayuanz3** [comment]
yes, it currently cannot be performed directly on .nii files, as it follows the structures in SAM2 (they process video as a sequences of images first). 
yes, processing 3D medical images involves treating them as sequences of 2D slices.
