### ISSUE TITLE
The differences with SAM2

### ISSUE THREAD

**Issue by Vanityplunde** [MedicineToken/Medical-SAM2#65]
Hello, author. Could you please clarify how the differences with SAM2 are reflected in the program? When I conduct the inference demonstration, am I using the MedSAM2 framework?

**Comment by jiayuanz3** [comment]
1. originally, sam2's 2d setting is similar to sam1. for the 2d implementation, we are introducing a new mechanism called 'memory bank' (refer to our paper: https://arxiv.org/abs/2408.00874 for details), to condition on template cases.
2. yes
