### ISSUE TITLE
Release of Medical-SAM2 pretrained weights

### ISSUE THREAD

**Issue by PRFina** [MedicineToken/Medical-SAM2#8]
Hi, and thanks for the amazing work done on the paper! Just wondering if there are any plans to release the weights of Medical-SAM2 fine-tuned on medical imaging data as shown in the paper

**Comment by jiayuanz3** [comment]
Sorry for the late reply. Pre-trained weight for 3D medical image can be found on our homepage. 2D pre-trained weight is one the way...
